export enum AppNotificationType {
  BP_REMINDER = 'BP_REMINDER',
  INACTIVITY_REMINDER = 'INACTIVITY_REMINDER',
  URGENT_INACTIVITY_REMINDER = 'URGENT_INACTIVITY_REMINDER',
  FOLLOW_UP_RECHECK = 'FOLLOW_UP_RECHECK',
  FOLLOW_UP_SEEK_CARE = 'FOLLOW_UP_SEEK_CARE',
  FOLLOW_UP_MISSED = 'FOLLOW_UP_MISSED',
  TREND_ALERT = 'TREND_ALERT',
  ESCALATION_ALERT = 'ESCALATION_ALERT',
  SESSION_EXPIRY = 'SESSION_EXPIRY',
  GENERIC = 'GENERIC',
}
